name: This is shared-library fo Git-Hub-actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [workflow_call]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "This is step1"
