name: This is shared-library fo Git-Hub-actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [workflow_call]
jobs:
  job1:
    runs-on: ubuntu-latest
    env: 
      environment: ${{ github.event.inputs.name }}
    steps:
      - name: Dev
        run: echo "This is Dev-Stage"
        if: ${{ env.environment == 'DEV' }}
      - name: Qa
        run: echo "This is Qa-Stage"
        if: ${{ env.environment == 'QA' }}
      - name: Prod
        run: echo "This is Prod-Stage"
        if: ${{ env.environment == 'PROD' }}
