name: This is shared-library fo Git-Hub-actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [workflow_call]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dev
        run: echo "This is Dev-Stage"
      - name: Qa
        run: echo "This is Dev-Stage"
      - name: Prod
        run: echo "This is Dev-Stage" 
